
development:
  adapter: postgis
  encoding: unicode
  pool: 5
  database: lame_development
  host: localhost
  username: lame_dev
  password: postgres
  su_username: postgres
  su_password: thisshouldbeasecurepasswordbutimtoolazy
  schema_search_path: public

test:
  adapter: postgis
  encoding: unicode
  pool: 5
  database: lame_test
  host: localhost
  username: lame_test
  password: postgres
  su_username: postgres
  su_password: thisshouldbeasecurepasswordbutimtoolazy
  schema_search_path: public
