name             'lame'
maintainer       'Markus Klepp'
maintainer_email 'kh0r@entwicklerbier.org'
license          'All rights reserved'
description      'Installs/Configures LAME'
long_description 'Installs/Configures LAME'
version          '0.1.0'

depends 'apt', '~> 2.6.0'
depends 'locale', '~> 1.0.2'
depends 'htop', '~> 2.0.0'
depends 'timezone-ii', '~> 0.2.0'
depends 'vim', '~> 1.1.2'
depends 'ruby_install', '~> 1.0.4'
depends 'chruby', '~> 0.2.2'
depends 'database', '~> 2.3.0'
depends 'postgresql', '~> 3.4.10'
depends 'postgis', '~> 0.3.0'
depends 'git', '~> 4.0.2'
depends 'redis2', '~> 0.5.1'
