# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.hostname = 'lame.local'

  config.vm.synced_folder '../', '/var/www/lame/current/', type: 'nfs'

  config.vm.network 'private_network', ip: '33.33.33.15'

  config.omnibus.chef_version = '11.16.2'

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "./Berksfile"

  config.vm.provision :chef_solo do |chef|

    chef.run_list = %w(recipe[lame::dev])

    chef.json = {
      database: {
        create: [
          {
            env: 'development',
            name: 'lame_development',
            username: 'lame_dev',
            password: 'postgres'
          },
          {
            env: 'test',
            name: 'lame_test',
            username: 'lame_test',
            password: 'postgres'
          }
        ]
      }

    }
  end
end
